version: '3.3'
services:
  postgres:
    container_name: postgres_db
    image: postgres:9.6.2
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_MULTIPLE_DATABASES="booking-api","booking-analyst"
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ../docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - ./docker-volumes/postgresql:/var/lib/postgresql
  booking-api:
    build: ./booking-api
    container_name: booking-api
    restart: always
    environment:
      - NODE_ENV=production
      - DB_PORT=5432
      - DB_HOST=postgres
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
  booking-frontend:
    build: ./booking-frontend
    container_name: booking-frontend
    restart: always
    environment:
      - NODE_ENV=production
      - API_HOST=booking-api
      - API_PORT=3000
    depends_on:
      - 'booking-api'
    ports:
      - '4000:80'
